github: [ajoydas, codemaster123]
patreon: ajoydev
open_collective: open-source-hub
ko_fi: ajoycoffee
tidelift: npm/your-package-name
community_bridge: cloud-foundry
liberapay: ajoydas
issuehunt: ajoyopensource
lfx_crowdfunding: cloud-foundry
polar: ajoy-polar
buy_me_a_coffee: ajoy
thanks_dev: ajoydas
custom: ['https://yourwebsite.com/sponsor', 'https://anotherlink.com']
